TallinnTransportGpsDemo/WebApp/ViewModels/ErrorViewModel.cs
namespace WebApp.ViewModels
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
        
    }
}

TallinnTransportGpsDemo/WebApp/ViewModels/TransportationLocationViewModel.cs
using System.Collections;
using System.Collections.Generic;
using Domain;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WebApp.ViewModels
{
    //TODO: Show embed map on page
    public class TransportationLocationViewModel
    {
        public TransportationService TransportationService { get; set; }
        public List<TransportationService> TransportationList { get; set; } 
        public string ServiceNumber { get; set; }
        public string? ShowNumber { get; set; }
    }
}

TallinnTransportGpsDemo/WebApp/Controllers/TallinnController.cs
using System;
using System.Collections.Generic;
using DAL;
using Domain;
using Domain.Enums;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WebApp.ViewModels;
using Controller = Microsoft.AspNetCore.Mvc.Controller;

namespace WebApp.Controllers
{
    public class TallinnController : Controller
    {
        private readonly ILogger<TallinnController> _logger;
        private readonly DataContext _context;

        public TallinnController(ILogger<TallinnController> logger, DataContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
        
        //[HttpGet("{id}")] // Matches '/Home/Hello/{id}'
        public IActionResult Bus(string id)
        {
            var vm = new TransportationLocationViewModel();
            if (!String.IsNullOrEmpty(id))
            {
                vm = new TransportationLocationViewModel()
                {
                    TransportationList = new List<TransportationService>(_context.TransportationPark.TransportationList.FindAll(tr => tr.Number == id && tr.Type == TransportationType.Bus)),
                    ServiceNumber = id
                };
            }
            return View(vm);
        }

        public IActionResult Tram(string id)
        {
            var vm = new TransportationLocationViewModel();
            if (!String.IsNullOrEmpty(id))
            {
                vm = new TransportationLocationViewModel()
                {
                    TransportationList = new List<TransportationService>(_context.TransportationPark.TransportationList.FindAll(tr => tr.Number == id && tr.Type == TransportationType.Tram)),
                    ServiceNumber = id
                };
            }
            return View(vm);
        }
        
        public IActionResult TrolleyBus(string id)
        {
            var vm = new TransportationLocationViewModel();
            if (!String.IsNullOrEmpty(id))
            {
                vm = new TransportationLocationViewModel()
                {
                    TransportationList = new List<TransportationService>(_context.TransportationPark.TransportationList.FindAll(tr => tr.Number == id && tr.Type == TransportationType.TrolleyBus)),
                    ServiceNumber = id
                };
            }
            return View(vm);
        }
    }
}

TallinnTransportGpsDemo/WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    <!--<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />-->
    <link rel="stylesheet" href="~/css/materialize.css" />
    <link rel="stylesheet" href="~/css/materialize.min.css" />
    <link rel="stylesheet" href="~/lib/leaflet/leaflet.css"
       integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
       crossorigin=""/>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
    <header>
        <nav>
            <div class="nav-wrapper #f1f8e9 light-green lighten-5">
              <a href="#!" class="brand-logo lime-text">Logo</a>
              <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons lime-text">menu</i></a>
              <ul class="right hide-on-med-and-down">
                <!--<li><a class="nav-link text-darken-3 lime-text hoverable" asp-area="" asp-controller="Tallinn" asp-action="Index">HOME</a></li>
                  <li><a class="nav-link text-darken-3 lime-text hoverable " asp-area="" asp-controller="Tallinn" asp-action="Privacy">PRIVACY</a></li>-->
                <li><a class="nav-link text-darken-3 lime-text hoverable " asp-area="" asp-controller="Tallinn" asp-action="Bus">BUSS</a></li>
                <li><a class="nav-link text-darken-3 lime-text hoverable " asp-area="" asp-controller="Tallinn" asp-action="Tram">TRAMM</a></li>
                <li><a class="nav-link text-darken-3 lime-text hoverable " asp-area="" asp-controller="Tallinn" asp-action="TrolleyBus">TROLL</a></li>
              </ul>
            </div>
          </nav>
        
          <ul class="sidenav" id="mobile-demo #9e9d24 lime darken-3">
            <li><a class="nav-link text-dark lime-text text-capitalize" asp-area="" asp-controller="Tallinn" asp-action="Index">Home</a></li>
            <li><a class="nav-link text-dark lime-text text-capitalize" asp-area="" asp-controller="Tallinn" asp-action="Privacy">Privacy</a></li>
          </ul>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - WebApp - <a asp-area="" asp-controller="Tallinn" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <!--<script src="~/lib/jquery/dist/jquery.min.js"></script>-->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <!--<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>-->
    <script src="~/js/materialize.js" asp-append-version="true"></script>
    <script src="~/js/materialize.min.js" asp-append-version="true"></script>
    <script src="~/lib/leaflet/leaflet.js" asp-append-version="true"
   integrity="sha512-GffPMF3RvMeYyc1LWMHtK8EbPv0iNZ8/oTtHPx9/cc2ILxQ+u905qIwdpULaqDkyBKgOaB57QTMg7ztg8Jm2Og=="
   crossorigin=""></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

TallinnTransportGpsDemo/WebApp/Views/Tallinn/Bus.cshtml
@model WebApp.ViewModels.TransportationLocationViewModel

@{
    ViewData["Title"] = "Bus Page";
}
<br/>
<br/>
<div class="row">
    <form asp-controller="Tallinn" asp-action="Bus" class="col s5" method="get">
        <div class="row valign-wrapper">
            <div class="input-field col s12">
                <i class="material-icons prefix">directions_bus</i>
                <textarea id="transportation_number" class="materialize-textarea" name="id" value="@Model.ServiceNumber"></textarea>
                <label for="transportation_number">Transpordi liininumber</label>
            </div>
            <button class="btn-floating pulse waves-effect waves-light #f1f8e9 light-green" 
                    type="submit">Otsi
                <i class="material-icons right">send</i>
            </button>
        </div>
    </form>
</div>

<div class="row">
    <div class="col s6">
        @if (Model.TransportationList != null)
        {
            <p>LK-laiuskraad PK-pikkuskraad</p>
            @foreach (var transport in Model.TransportationList)
            {
                <!--<a class="waves-effect waves-light" href="https://www.google.com/maps/search/?api=1&query=@Html.DisplayFor(elem => transport.Coordinate.Longitude),@Html.DisplayFor(elem => transport.Coordinate.Latitude)">-->
                <a class="btn col s12 waves-effect waves-light #f1f8e9 light-green lighten-3 z-depth-1 hoverable" href="https://www.google.com/maps/search/?api=1&query=@Html.DisplayFor(elem => transport.Coordinate.Latitude),@Html.DisplayFor(elem => transport.Coordinate.Longitude)">
                    <div class="row">
                        <i class="col s1 material-icons">directions_bus</i>
                        <div class="col s2">
                            @Html.DisplayFor(elem => transport.Number)
                        </div>
                        <div class="col s4">
                            LK: @Html.DisplayFor(elem => transport.Coordinate.Latitude)
                        </div>
                        <div class="col s5">
                            PK: @Html.DisplayFor(elem => transport.Coordinate.Longitude)
                        </div>
                    </div>
                </a>

                <!--</a>-->
            }
        }
    </div>
    <div class="col s6">
            
        </div>
</div>


<br/>
<br/>
<label>Tallinn Transportation:</label>  @ViewBag.AllTransportation

TallinnTransportGpsDemo/WebApp/Views/Tallinn/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

TallinnTransportGpsDemo/WebApp/Views/Tallinn/Tram.cshtml
@model WebApp.ViewModels.TransportationLocationViewModel

@{
    ViewData["Title"] = "Bus Page";
}
<br/>
<br/>
<div class="row">
    <form asp-controller="Tallinn" asp-action="Tram" class="col s5" method="get">
        <div class="row valign-wrapper">
            <div class="input-field col s12">
                <i class="material-icons prefix">tram</i>
                <textarea id="transportation_number" class="materialize-textarea" name="id" value="@Model.ServiceNumber"></textarea>
                <label for="transportation_number">Transpordi liininumber</label>
            </div>
            <button class="btn-floating pulse waves-effect waves-light #f1f8e9 light-green" 
                    type="submit">Otsi
                <i class="material-icons right">send</i>
            </button>
        </div>
    </form>
</div>

<div class="row">
    <div class="col s6">
        @if (Model.TransportationList != null)
        {
            <p>LK-laiuskraad PK-pikkuskraad</p>
            @foreach (var transport in Model.TransportationList)
            {
                <!--<a class="waves-effect waves-light" href="https://www.google.com/maps/search/?api=1&query=@Html.DisplayFor(elem => transport.Coordinate.Longitude),@Html.DisplayFor(elem => transport.Coordinate.Latitude)">-->
                <a class="btn col s12 waves-effect waves-light #f1f8e9 light-green lighten-3 z-depth-1 hoverable" href="https://www.google.com/maps/search/?api=1&query=@Html.DisplayFor(elem => transport.Coordinate.Latitude),@Html.DisplayFor(elem => transport.Coordinate.Longitude)">
                    <div class="row">
                    <i class="col s1 material-icons">directions_bus</i>
                    <div class="col s2">
                        @Html.DisplayFor(elem => transport.Number)
                    </div>
                        <div class="col s4">
                            LK: @Html.DisplayFor(elem => transport.Coordinate.Latitude)
                        </div>
                        <div class="col s5">
                            PK: @Html.DisplayFor(elem => transport.Coordinate.Longitude)
                        </div>
                    </div>
                </a>

        <!--</a>-->
            }
        }
    </div>
    <div class="col s6">
        
    </div>
</div>
<br/>
<br/>
<label>Tallinn Transportation:</label>  @ViewBag.AllTransportation

TallinnTransportGpsDemo/WebApp/Views/Tallinn/TrolleyBus.cshtml
@model WebApp.ViewModels.TransportationLocationViewModel

@{
    ViewData["Title"] = "Bus Page";
}
<br/>
<br/>
<div class="row">
    <form asp-controller="Tallinn" asp-action="TrolleyBus" class="col s5" method="get">
        <div class="row valign-wrapper">
            <div class="input-field col s12">
                <i class="material-icons prefix">directions_bus</i>
                <textarea id="transportation_number" class="materialize-textarea" name="id" value="@Model.ServiceNumber"></textarea>
                <label for="transportation_number">Transpordi liininumber</label>
            </div>
            <button class="btn-floating pulse waves-effect waves-light #f1f8e9 light-green" 
                    type="submit">Otsi
                <i class="material-icons right">send</i>
            </button>
        </div>
    </form>
</div>

<div class="row">
    <div class="col s6">
        @if (Model.TransportationList != null)
        {
            <p>LK-laiuskraad PK-pikkuskraad</p>
            @foreach (var transport in Model.TransportationList)
            {
                <!--<a class="waves-effect waves-light" href="https://www.google.com/maps/search/?api=1&query=@Html.DisplayFor(elem => transport.Coordinate.Longitude),@Html.DisplayFor(elem => transport.Coordinate.Latitude)">-->
                <a class="btn col s12 waves-effect waves-light #f1f8e9 light-green lighten-3 z-depth-1 hoverable" href="https://www.google.com/maps/search/?api=1&query=@Html.DisplayFor(elem => transport.Coordinate.Latitude),@Html.DisplayFor(elem => transport.Coordinate.Longitude)">
                    <div class="row">
                        <i class="col s1 material-icons">directions_bus</i>
                        <div class="col s2">
                            @Html.DisplayFor(elem => transport.Number)
                        </div>
                        <div class="col s4">
                            LK: @Html.DisplayFor(elem => transport.Coordinate.Latitude)
                        </div>
                        <div class="col s5">
                            PK: @Html.DisplayFor(elem => transport.Coordinate.Longitude)
                        </div>
                    </div>
                </a>
                <!--</a>-->
            }
        }
    </div>
    <div class="col s6">
        
    </div>
</div>

<br/>
<br/>
<label>Tallinn Transportation:</label>  @ViewBag.AllTransportation